#ifndef ESP32_XBEE_TASKS_H
#define ESP32_XBEE_TASKS_H

#define TASK_PRIORITY_STATUS_LED 0
#define TASK_PRIORITY_RESET_BUTTON 0
#define TASK_PRIORITY_NTRIP 5
#define TASK_PRIORITY_UART 10

#endif //ESP32_XBEE_TASKS_H
