#ifndef ESP32_XBEE_TASKS_H
#define ESP32_XBEE_TASKS_H

#define TASK_PRIORITY_STATUS_LED 0
#define TASK_PRIORITY_RESET_BUTTON 0
#define TASK_PRIORITY_WIFI_STATUS 0
#define TASK_PRIORITY_STATS 0
#define TASK_PRIORITY_INTERFACE 5
#define TASK_PRIORITY_UART 10
#define TASK_PRIORITY_MAX 100

#endif //ESP32_XBEE_TASKS_H
